export const menuItems = [
  {
    id: 2,
    code: "IA",
    title: "아이스 아메리카노",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 3000,
  },
  {
    id: 2,
    code: "CF",
    title: "소풍컵과일",
    type: "none",
    option: "none",
    size: "레귤러",
    price: 3500,
  },
  {
    id: 6,
    code: "MG",
    title: "미숫가루",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 3500,
  },
  {
    id: 4,
    code: "PFA",
    title: "패션후르츠",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 4000,
  },
  {
    id: 3,
    code: "LMA",
    title: "레몬에이드",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 3000,
  },
  {
    id: 5,
    code: "MC",
    title: "연아아이스커피",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 2500,
  },
];
