export const menuItems = [
  {
    id: 0,
    code: "HA",
    title: "아메리카노",
    type: "핫",
    option: "none",
    size: "레귤러",
    price: 2500,
  },
  {
    id: 1,
    code: "IA",
    title: "아이스 아메리카노",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 2500,
  },
  {
    id: 2,
    code: "CF",
    title: "소풍컵과일",
    type: "none",
    option: "none",
    size: "레귤러",
    price: 3500,
  },
  {
    id: 6,
    code: "MG",
    title: "미숫가루",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 3500,
  },
  {
    id: 4,
    code: "PFA",
    title: "패션후르츠",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 4000,
  },
  {
    id: 7,
    code: "JM",
    title: "자몽에이드",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 3000,
  },
  {
    id: 7,
    code: "ORG",
    title: "오렌지쥬스",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 2000,
  },
  {
    id: 3,
    code: "LMA",
    title: "레몬에이드",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 3000,
  },
  {
    id: 5,
    code: "MC",
    title: "아이스 다방커피",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 3000,
  },
  {
    id: 8,
    code: "CK",
    title: "쿠키",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 1500,
  },
  {
    id: 9,
    code: "DAL",
    title: "달고나",
    type: "아이스",
    option: "none",
    size: "레귤러",
    price: 1500,
  },
];
